### ISSUE TITLE
Inability to add a new location

### ISSUE THREAD

**Issue by swarnap** [AimHigher-Web-Design/tech-outsiders#19]
I'm based in San Francisco Bay Area, California.  This location is not listed and I, therefore, couldn't finish adding my profile there.

**Comment by amykapernick** [comment]
Hi @swarnap. We've originally started in Australia but I'm speaking with @msandfor about expanding to allow new locations.

**Comment by amykapernick** [comment]
@swarnap we've just pushed through a change for this, you can now add new locations. I've added one for San Francisco so you should be good to finish your profile!

**Comment by amykapernick** [comment]
This can now be done after merging in PR #27
